In [2]:

!pip install numpy


error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.14/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detai

In [17]:
import numpy as np

data = np.random.rand(2, 3)
print(data.ndim) 

2


In [18]:
print(data.shape)

(2, 3)


In [19]:
print(data.ndim)

2


In [20]:
data.shape

(2, 3)

In [21]:
py_list=[1,2,3]
print("multiplication", py_list*2)

multiplication [1, 2, 3, 1, 2, 3]


In [24]:
py_array=np.array([1,2,3])
print("multiplication", py_list*2)

multiplication [1, 2, 3, 1, 2, 3]


In [35]:
import time
start=time.time()

py_list=[i*2 for i in range(100000)]

print("time taken is :    ", time.time()-start)

time taken is :     0.02147960662841797


In [36]:
import time
start=time.time()

np_array=np.arange(1000)*2

print("time taken is :    ", time.time()-start)

time taken is :     0.0004086494445800781


In [32]:
np_array.ndim

1

In [37]:
sys.maxsize

9223372036854775807

In [38]:
import sys
print(sys.maxsize)


9223372036854775807


In [40]:
zeros=np.zeros((2,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
one=np.ones((2,3))
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
full=np.full((2,3),7)
full

array([[7, 7, 7],
       [7, 7, 7]])

In [45]:
random=np.random.random((2,3))
random

array([[0.51610904, 0.68865346, 0.29496003],
       [0.36093928, 0.34872271, 0.24555343]])

In [48]:
sequence=np.arange(0,11,2)
sequence

array([ 0,  2,  4,  6,  8, 10])